import type { Metadata } from 'next'
import Nav from '@/components/nav'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: 'Terms of Service — FORGE',
  description: 'Terms of service for FORGE by NorwegianSpark SA.',
  robots: { index: false, follow: true },
}

export default function TermsPage() {
  return (
    <>
      <Nav />
      <div className="pt-14">
        <div className="max-w-3xl mx-auto px-4 py-16">
          <h1 className="text-3xl font-medium text-[--text-primary] mb-2">Terms of Service</h1>
          <p className="text-sm text-[--text-muted] mb-10 font-mono">Last updated: April 2026</p>

          <div className="space-y-8 text-sm text-[--text-secondary] leading-relaxed">
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Service</h2>
              <p>FORGE is an AI-powered code generation tool operated by NorwegianSpark SA. By using FORGE, you agree to these terms.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Code ownership</h2>
              <p>You own the code generated by FORGE. You may use it for any purpose, including commercial products. NorwegianSpark SA claims no rights over your generated output.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Acceptable use</h2>
              <p>Do not use FORGE to generate malicious code, spam, or content that violates applicable law. Do not attempt to circumvent rate limits or abuse the API.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Subscriptions and billing</h2>
              <p>Paid plans are billed monthly. Cancel anytime — access continues until end of the billing period. Refunds are handled case by case; contact norwegianspark@gmail.com.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Service availability</h2>
              <p>We aim for high availability but make no SLA guarantees on free plans. Pro and Agency plan holders may contact support for incident response.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Limitation of liability</h2>
              <p>FORGE provides generated code &quot;as is&quot;. Review all generated code before deploying to production. NorwegianSpark SA is not liable for issues arising from your use of generated code.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Governing law</h2>
              <p>These terms are governed by Norwegian law. Disputes are resolved in Norwegian courts.</p>
            </section>
            <section>
              <h2 className="text-[--text-primary] font-medium text-base mb-3">Contact</h2>
              <p>NorwegianSpark SA · Org no: 834 984 172 · norwegianspark@gmail.com · +47 99 73 74 67</p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}
