const QUALITY_STANDARDS = `
STRICT REQUIREMENTS — every generation MUST follow these:
- Next.js 15 App Router with TypeScript strict mode — zero \`any\` types
- Tailwind CSS only for styling — no CSS files except globals.css
- Use next/image exclusively for images — add priority prop on hero images, placeholder="blur" with blurDataURL
- Always \`await params\` in dynamic route handlers and pages (Next.js 15 breaking change)
- Include generateMetadata() on every route with unique title ≤ 60 chars
- Include app/sitemap.ts, app/robots.ts, app/not-found.tsx, app/error.tsx
- Include .env.example listing all required environment variables
- Include README.md with setup + deploy instructions for Vercel, Cloudflare Pages, and Netlify

FORBIDDEN:
- Dark navy (#0A0F1E) backgrounds — NEVER use this color
- react-icons package — use lucide-react instead
- moment.js — use native Date or date-fns
- Inline hex colors outside CSS variables or Tailwind config
- inline styles — Tailwind classes only
`

const FREE_ADDITIONS = `
Generated by FORGE — AI App Builder by NorwegianSpark SA
Include "Built with FORGE" comment in the footer of generated code.
`

const PRO_ADDITIONS = `
Include detailed deploy instructions:
- Vercel: vercel --prod
- Cloudflare Pages: npx wrangler pages deploy .next
- Netlify: netlify deploy --prod
Include CI/CD GitHub Actions workflow file.
`

function agencyAdditions(brandName?: string, logoUrl?: string, primaryColor?: string): string {
  const brand = brandName || "FORGE"
  const parts = [PRO_ADDITIONS]
  parts.push(`\nWHITE-LABEL BRANDING:`)
  parts.push(`- Brand name: "${brand}" — use this in all headers, footers, and meta tags instead of "FORGE"`)
  if (logoUrl) parts.push(`- Logo URL: ${logoUrl}`)
  if (primaryColor) parts.push(`- Primary brand color: ${primaryColor} — use for buttons, accents, and highlights`)
  parts.push(`- Do NOT mention "FORGE" or "NorwegianSpark" anywhere in the generated code`)
  return parts.join("\n")
}

export type Plan = "free" | "pro" | "agency"

export function getSystemPrompt(
  plan: Plan,
  style?: string,
  whiteLabel?: { brandName?: string; logoUrl?: string; primaryColor?: string }
): string {
  const parts = [
    `You are FORGE, an expert full-stack engineer. Output production-ready Next.js 15 App Router TypeScript + Tailwind code.`,
    style ? `Design style: ${style}.` : "",
    QUALITY_STANDARDS,
  ]

  switch (plan) {
    case "free":
      parts.push(FREE_ADDITIONS)
      break
    case "pro":
      parts.push(PRO_ADDITIONS)
      break
    case "agency":
      parts.push(agencyAdditions(whiteLabel?.brandName, whiteLabel?.logoUrl, whiteLabel?.primaryColor))
      break
  }

  return parts.filter(Boolean).join("\n\n")
}

export const MODEL_CONFIG: Record<Plan, { model: string; maxTokens: number }> = {
  free: { model: "claude-haiku-4-5-20251001", maxTokens: 1500 },
  pro: { model: "claude-sonnet-4-6", maxTokens: 4000 },
  agency: { model: "claude-opus-4-7", maxTokens: 8000 },
}

export const TOKEN_PRICING: Record<string, { inputPerMtok: number; outputPerMtok: number }> = {
  "claude-haiku-4-5-20251001": { inputPerMtok: 1_00, outputPerMtok: 5_00 },
  "claude-sonnet-4-6": { inputPerMtok: 3_00, outputPerMtok: 15_00 },
  "claude-opus-4-7": { inputPerMtok: 15_00, outputPerMtok: 75_00 },
}

export function calculateCostCents(model: string, inputTokens: number, outputTokens: number): number {
  const pricing = TOKEN_PRICING[model]
  if (!pricing) return 0
  const inputCost = (inputTokens / 1_000_000) * pricing.inputPerMtok
  const outputCost = (outputTokens / 1_000_000) * pricing.outputPerMtok
  return Math.ceil(inputCost + outputCost)
}
