export const revalidate = 86400
export const metadata = { title: "Disclosure" }

export default function DisclosurePage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-16 prose prose-invert">
      <h1 className="text-3xl md:text-4xl font-semibold tracking-tight mb-4">Disclosure</h1>
      <p className="text-lg text-zinc-400 leading-relaxed mb-8">
        Transparency is important to us. Here&apos;s what you should know about FORGE.
      </p>

      <h2 className="text-2xl font-semibold mt-10 mb-3">Affiliate relationships</h2>
      <p className="text-zinc-300 leading-relaxed">
        FORGE may contain links to third-party services. Some of these links may be affiliate links, meaning we earn a small commission if you sign up through them at no extra cost to you. This does not affect our recommendations or the code we generate.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">AI-generated code</h2>
      <p className="text-zinc-300 leading-relaxed">
        All code generated by FORGE is created by Anthropic&apos;s Claude AI models. While we enforce strict quality standards in our system prompts, AI-generated code should be reviewed before use in production. FORGE is a tool to accelerate development, not a replacement for human oversight.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">Pricing and billing</h2>
      <p className="text-zinc-300 leading-relaxed">
        Subscription prices are in USD and billed monthly via Stripe. You can cancel at any time. We do not store credit card details — all payment processing is handled by Stripe.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-3">Data usage</h2>
      <p className="text-zinc-300 leading-relaxed">
        Your prompts are sent to Anthropic&apos;s API for code generation. We store generation history in our database to provide you with project history and usage tracking. We do not sell your data or use it for any purpose other than providing the FORGE service.
      </p>

      <p className="mt-12 text-xs text-zinc-500">NorwegianSpark SA · Org no: 834 984 172 · Last updated: April 2026</p>
    </div>
  )
}
